name: PHP CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, intl, gd, xml, zip, dom, curl, fileinfo, json, mysqli, pdo_mysql, soap, xml, xmlreader, xmlwriter, xsl, zip, bcmath, exif, iconv, imagick, opcache, pcntl, pdo, pdo_sqlite, phar, posix, readline, sqlite3, tokenizer, xml, xsl, zip, zlib
          coverage: none
          tools: composer:v2
      - name: Install dependencies
        run: composer dump-autoload --optimize
  deployment:
    # all files tar gz and upload to server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, intl, gd, xml, zip, dom, curl, fileinfo, json, mysqli, pdo_mysql, soap, xml, xmlreader, xmlwriter, xsl, zip, bcmath, exif, iconv, imagick, opcache, pcntl, pdo, pdo_sqlite, phar, posix, readline, sqlite3, tokenizer, xml, xsl, zip, zlib
          coverage: none
          tools: composer:v2
      - name: Install dependencies
        run: composer dump-autoload --optimize
      - name: Upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "."
          target: "/var/www/elbekjohn/data/www/khamdullaev.tech"
          strip_components: 1
