name: PHP CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, intl, gd, xml, zip, dom, curl, fileinfo, json, mysqli, pdo_mysql, soap, xml, xmlreader, xmlwriter, xsl, zip, bcmath, exif, iconv, imagick, opcache, pcntl, pdo, pdo_sqlite, phar, posix, readline, sqlite3, tokenizer, xml, xsl, zip, zlib
          coverage: none
          tools: composer:v2
      - name: Install dependencies
        run: composer dump-autoload --optimize
  # zip the files and push to the server
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, intl, gd, xml, zip, dom, curl, fileinfo, json, mysqli, pdo_mysql, soap, xml, xmlreader, xmlwriter, xsl, zip, bcmath, exif, iconv, imagick, opcache, pcntl, pdo, pdo_sqlite, phar, posix, readline, sqlite3, tokenizer, xml, xsl, zip, zlib
          coverage: none
          tools: composer:v2
      - name: Install dependencies
        run: composer dump-autoload --optimize
      - name: Zip files
        run: zip -r -X -q -9 -o -y -j -i *
      - name: Upload files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "*.zip"
          target: "/var/www/elbekjohn/www/khamdullaev.tech"
          script: "unzip -o *.zip && rm -rf *.zip"
