name: PHP CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, intl, gd, xml, zip, dom, curl, fileinfo, json, mysqli, pdo_mysql, soap, xml, xmlreader, xmlwriter, xsl, zip, bcmath, exif, iconv, imagick, opcache, pcntl, pdo, pdo_sqlite, phar, posix, readline, sqlite3, tokenizer, xml, xsl, zip, zlib
          coverage: none
          tools: composer:v2
      - name: Install dependencies
        run: composer dump-autoload --optimize
  # zip the files and push to the server
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, intl, gd, xml, zip, dom, curl, fileinfo, json, mysqli, pdo_mysql, soap, xml, xmlreader, xmlwriter, xsl, zip, bcmath, exif, iconv, imagick, opcache, pcntl, pdo, pdo_sqlite, phar, posix, readline, sqlite3, tokenizer, xml, xsl, zip, zlib
          coverage: none
          tools: composer:v2
      - name: Install dependencies
        run: composer dump-autoload --optimize
      - name: Zip files
        run: tar -zcvf khamdullaev.tech.tar.gz ./
      # clear host files
      - name: Clear host files
        run: ssh -i ${{ secrets.SSH_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf /var/www/elbekjohn/data/khamdullaev.tech/*"
      # upload files to host
      - name: Upload files to host
        run: scp -i ${{ secrets.SSH_KEY }} khamdullaev.tech.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/elbekjohn/data/khamdullaev.tech/
      # extract files
      - name: Extract files
        run: ssh -i ${{ secrets.SSH_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "tar -zxvf /var/www/elbekjohn/data/khamdullaev.tech/khamdullaev.tech.tar.gz -C /var/www/elbekjohn/data/khamdullaev.tech/"
      # remove zip file
      - name: Remove zip file
        run: ssh -i ${{ secrets.SSH_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf /var/www/elbekjohn/data/khamdullaev.tech/khamdullaev.tech.tar.gz"
